# Generated by Django 4.2.2 on 2023-08-13 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steponava', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budas',
            options={'verbose_name': 'Būdas', 'verbose_name_plural': 'Būdai'},
        ),
        migrations.AlterModelOptions(
            name='lapas',
            options={'verbose_name': 'Lapas', 'verbose_name_plural': 'Lapai'},
        ),
        migrations.AlterModelOptions(
            name='lapasinstance',
            options={'verbose_name': 'Išduotas lapas', 'verbose_name_plural': 'Išduoti lapai'},
        ),
        migrations.AlterModelOptions(
            name='vadovas',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Vadovas', 'verbose_name_plural': 'Vadovai'},
        ),
        migrations.AlterField(
            model_name='lapas',
            name='budas',
            field=models.ForeignKey(help_text='Parinkite medžiojimo būdą', null=True, on_delete=django.db.models.deletion.SET_NULL, to='steponava.budas'),
        ),
    ]
